### PR TITLE
resolved error when using CORS for image source

### PR DESCRIPTION
**Pull request by pclowes**
By adding source.crossOrigin = $$.attr("crossorigin"), to line 16535 the face detection will now work with images that are hosted elsewhere such as AWS S3 without CORS issues.

### CODE REVIEW

**Comment by jaysalvat** [comment]
Great!
I can't use your pull request. The fixes must be done in src/ before building /dist.
I will try to make the change today on master and make a new release ASAP.

Thanks!

**Comment by jaysalvat** [comment]
Hello,
I add your fix in a new branch.
https://github.com/jaysalvat/jquery.facedetection/tree/cors

I can't really test it.
Can you please confirm it fixes your problem?

**Comment by pclowes** [comment]
Testing now, one important fix is that the crossorigin attribute on the image src must be set to: `crossorigin="anonymous"` or else it will take two clicks of the detection button for detection to occur. While this follows from the last fix it is a relatively unknown image attribute. I have just pushed this change as well.

**Comment by jaysalvat** [comment]
Hello,

After several tries, I didn't manage te reproduce and test that issue.
But if you say me it fixes your problem, I release it.

Do you confirm it works for you?

**Pull request closed without merging**
